const gsmKpis = [
    "G01_Availability Cell (%)",
    "G02_Availability TCH (%)",
    "G03_CSSR (%)",
    "G04_SD Blocked Rate (%)",
    "G05_SD Drop Rate (%)",
    "G06_TCH Assignment SR (%)",
    "G07_TCH Blocked Rate (%)",
    "G08_TCH Drop Rate (%)",
    "G09_PDCH Establishment SR (%)",
    "G10_PDCH Congestion Rate (%)",
    "G10_PDCH Block (#)",
    "G11_DL TBF Establishment SR (%)",
    "G12_UL TBF Establishment SR (%)",
    "G13_PS Drop Rate (%)",
    "G13_DL TBF Drop Rate (%)",
    "G14_PS Traffic (GBytes)",
    "G15_TCH Traffic (Erl)",
    "G16_SDCCH Traffic (Erl)",
    "G17_Handover SR (%)",
    "G18_ICM Band 1 (%)",
    "G19_ICM Band 2 (%)",
    "G20_ICM Band 3 (%)",
    "G21_ICM Band 4 (%)",
    "G22_ICM Band 5 (%)",
    "G23_Bad ICM (%)",
    "G25_Rx Qual DL Good (%)",
    "G26_Rx Qual DL Bad (%)",
    "G28_Rx Qual UL Good (%)",
    "G29_Rx Qual UL Bad (%)",
    "G31_SQI Good DL (%)",
    "G32_SQI Accpt DL (%)",
    "G33_SQI Bad DL (%)",
    "G35_SQI Good UL (%)",
    "G36_SQI Accpt UL (%)",
    "G37_SQI Bad UL (%)",
    "G39_2G to 4G Fast Return (#)"
]
const lteKpis = [
    "L02_RRC CSSR (%)",
    "L03_RRC CSSR Serv (%)",
    "L04_ERAB CSSR (%)",
    "L05_ERAB DR (%)",
    "L06_ERAB DR (%)",
    "L07_Packet Loss Rate DL (%)",
    "L08_Packet Loss Rate UL (%)",
    "L09_IAF HO Prep SR (%)",
    "L09_IAF HO Exe SR (%)",
    "L10_IEF HO Prep SR (%)",
    "L10_IEF HO Exe SR (%)",
    "L11_Intra LTE HO Prep SR (%)",
    "L11_Intra LTE HO Exe SR (%)",
    "L12_IRAT HOSR (%)",
    "L13_Cell NotAvail (%)",
    "L15_Integrity DL Latency (ms)",
    "L16_Avg DL Thp Cell (Mbps)",
    "L17_Avg UL Thp Cell (Mbps)",
    "L18_Avg DL Thp User (Mbps)",
    "L19_Avg UL Thp User (Mbps)",
    "L20_Active UE User (#)",
    "L21_Avg RRC User (#)",
    "L21_Max RRC User (#)",
    "L22_Avg ERAB User (#)",
    "L22_Max ERAB User (#)",
    "L23_Avg UL Interference PUSCH (dBm)",
    "L23_Avg UL Interference PUCCH (dBm)",
    "L24_PRB Util DL (%)",
    "L25_PRB Util UL (%)",
    "L26_CA User (#)",
    "L27_CA Capable User (#)",
    "L29_CA Thpt (Mbps)",
    "L30_DL BLER (%)",
    "L31_UL BLER (%)",
    "L33_Average CQI (#)",
    "L34_Average RSRP (dBm)",
    "L35_RSRP <-110 dBm (%)",
    "L36_Average SINR PUSCH (dB)",
    "L36_Average SINR PUCCH (dB)",
    "L37_Spectral Efficiency (Bit/s/Hz)",
    "S01_Accessibility SIP QCI5 (%)",
    "S01_Retainability SIP QCI5 (%)",
    "S01_RRC Re-estab SR QCI5 (%)",
    "V01_E-RAB Establisment SR QCI1 (%)",
    "V02_E-RAB Retainability QCI1 (%)",
    "V03_RRC Re-estab SR QCI1 (%)",
    "V06_VoLTE Packet Loss DL (%)",
    "V07_VoLTE Packet Loss UL (%)",
    "V08_VoLTE IAF HO SR (%)",
    "V09_VoLTE IEF HO SR (%)",
    "V11_VoLTE Integrity DL Latency (ms)",
    "V12_VoLTE Integrity Cell (%)",
    "V13_VoLTE Integrity UE (%)",
    "V14_DL Silent exp per VoLTE user (ms)",
    "V15_UL Silent exp per VoLTE user (ms)",
    "V16_SRVCC HO to GERAN Prep SR (%)",
    "V16_SRVCC HO to GERAN Exe SR (%)",
    "V17_SRVCC HO to GERAN Prep SR (%) PLMN0",
    "V17_SRVCC HO to GERAN Exe SR (%) PLMN0",
    "V18_SRVCC HO to UTRAN Prep SR (%)",
    "V18_SRVCC HO to UTRAN Exe SR (%)",
    "L06_ERAB Drop due to Cell Down Time",
    "L06_ERAB Drop due to Cell Down Time (PNR)",
    "L06_ERAB Drop due to contact with UE lost",
    "L06_ERAB Drop due to HO Exe failure",
    "L06_ERAB Drop due to HO Preparation",
    "L06_ERAB Drop due to S1/X2 Down / Tn Res Unavail",
    "L06_ERAB Drop due to UE Pre-emption",
    "L14_PSDL Trf (GB)",
    "L14_PSUL Trf (GB)",
    "L32_Modulation DL QPSK (#)",
    "L32_Modulation DL 16QAM (#)",
    "L32_Modulation DL 64QAM (#)",
    "L32_Modulation DL 256QAM (#)",
    "V02_VoLTE Drop due to Cell Down Time",
    "V02_VoLTE Drop due to contact with UE lost",
    "V02_VoLTE Drop due to HO Exe Failure",
    "V02_VoLTE Drop due to HO Preparation",
    "V02_VoLTE Drop due to part. ERAB path switch fail",
    "V02_VoLTE Drop due to S1/X2 Down / Tn Res Unavail",
    "V04_VoLTE Traffic (Erlang)",
    "V05_VoLTE User (#)",
    "V10_RRC RwR CSFB L2G (#)",
    "V10_RRC RwR CSFB L2U (#)",
    "V10_CSFB Indicators Received (#) Denom",
    "V10_RRC RwR SC L2G (#)",
    "V10_RRC RwR SC L2U (#)",
    "V19_L2G SRVCC (%)",
    "V20_CSFB 2G (%)",
    "V21_VoLTE UL Audio Gap < 6s (%)",
    "V10_CSFB Initiation Success Rate (%)",
]

module.exports = {
    gsmKpis,
    lteKpis
};