GET https://api.eprojecttrackers.com/node/dnb/cellInfo?cellName={{cellName}}
X-Requested-With: XMLHttpRequest
API: {{apiKey}}
Accept: application/json



###
GET https://ndo-portal.eprojecttrackers.com/main.php?action=tabulatorPG&table=tblcellid2&view=1&boolOperand=AND&schema=rfdb&page=1&size=100
X-Requested-With: XMLHttpRequest
API: {{apiKey}}
Accept: application/json



###
GET http://localhost:3001/node/dnb/cellInfo?cellName={{cellName}}
X-Requested-With: XMLHttpRequest
API: {{apiKey}}
Accept: application/json
Cookie: API={{apiKey}}; PHPSESSID=64e81b0a24936cebb7890c3a2b39eeb8; Username=phanveehuen; Name=Phan+Vee+Huen; UserType=Admin; UserID=774

###
GET http://localhost:3001/node/dnb/v3/cellDailyLTE?cellId=DBGBK0173_L7_0010
X-Requested-With: XMLHttpRequest
API: {{apiKey}}
Accept: application/json
Cookie: API={{apiKey}}; PHPSESSID=64e81b0a24936cebb7890c3a2b39eeb8; Username=phanveehuen; Name=Phan+Vee+Huen; UserType=Admin; UserID=774

###
GET http://localhost:3001/node/dnb/v3/cellDailyLTE?cellId=DBGBK0173_L7_0010&format=csv
X-Requested-With: XMLHttpRequest
API: {{apiKey}}
Accept: application/json
Cookie: API={{apiKey}}; PHPSESSID=64e81b0a24936cebb7890c3a2b39eeb8; Username=phanveehuen; Name=Phan+Vee+Huen; UserType=Admin; UserID=774

###
GET http://localhost:3001/node/dnb/v3/cellDailyLTE?cellId=DBGBK0173_L7_0010
X-Requested-With: XMLHttpRequest
API: {{apiKey}}
Accept: application/json
Cookie: API={{apiKey}}; PHPSESSID=64e81b0a24936cebb7890c3a2b39eeb8; Username=phanveehuen; Name=Phan+Vee+Huen; UserType=Admin; UserID=774

###
GET http://localhost:3001/node/dnb/v3/cellDailyNR?cellId=DBPET1129_N3_0320
X-Requested-With: XMLHttpRequest
API: {{apiKey}}
Accept: application/json
Cookie: API={{apiKey}}; PHPSESSID=64e81b0a24936cebb7890c3a2b39eeb8; Username=phanveehuen; Name=Phan+Vee+Huen; UserType=Admin; UserID=774

###
GET http://localhost:3001/node/dnb/v3/cellDailyNR?cellId=DBPET1129_N3_0320&format=csv
X-Requested-With: XMLHttpRequest
API: {{apiKey}}
Accept: application/text
Cookie: API={{apiKey}}; PHPSESSID=64e81b0a24936cebb7890c3a2b39eeb8; Username=phanveehuen; Name=Phan+Vee+Huen; UserType=Admin; UserID=774

###
GET http://localhost:3001/node/dnb/v3/cellsList?format=csv
X-Requested-With: XMLHttpRequest
API: {{apiKey}}
Accept: application/text
Cookie: API={{apiKey}}; PHPSESSID=64e81b0a24936cebb7890c3a2b39eeb8; Username=phanveehuen; Name=Phan+Vee+Huen; UserType=Admin; UserID=774

###
GET http://localhost:3001/node/dnb/v3/networkDailyLTE?format=csv
X-Requested-With: XMLHttpRequest
API: {{apiKey}}
Accept: application/text
Cookie: API={{apiKey}}; PHPSESSID=64e81b0a24936cebb7890c3a2b39eeb8; Username=phanveehuen; Name=Phan+Vee+Huen; UserType=Admin; UserID=774

###
GET http://localhost:3001/node/dnb/
X-Requested-With: XMLHttpRequest
API: {{apiKey}}
Accept: application/text
Cookie: API={{apiKey}}; PHPSESSID=64e81b0a24936cebb7890c3a2b39eeb8; Username=phanveehuen; Name=Phan+Vee+Huen; UserType=Admin; UserID=774


###
GET http://localhost:3001/node/dnb/v3/networkDailyLTE
X-Requested-With: XMLHttpRequest
API: {{apiKey}}
Accept: application/text


###
GET http://localhost:3001/node/dnb/v3/clusterDailyLTE?clusterId=PGBK_03
X-Requested-With: XMLHttpRequest
API: {{apiKey}}
Accept: application/text

###
GET http://localhost:3001/node/dnb/v3/clusterStatsLTE?clusterId=PGBK_03
X-Requested-With: XMLHttpRequest
API: {{apiKey}}
Accept: application/json


###
GET http://localhost:3001/node/dnb/clusterStatsLTE?clusterId=PGBK_03
X-Requested-With: XMLHttpRequest
API: {{apiKey}}
Accept: application/text


###
GET https://api.eprojecttrackers.com/node/dnb/v3/clusterStatsLTE?clusterId=PGBK_03
X-Requested-With: XMLHttpRequest
API: {{apiKey}}
Accept: application/text


###
GET https://api.eprojecttrackers.com/node/dnb/networkDailyNR
X-Requested-With: XMLHttpRequest
API: {{apiKey}}
Accept: application/text


###
GET http://localhost:3001/node/dnb/v3/networkDailyNR
X-Requested-With: XMLHttpRequest
API: {{apiKey}}
Accept: application/text


###
GET http://localhost:3001/node/dnb/v3/statsForCustomCellsListNR2?cells[]=DWKUL0239_N3_0330&cells[]=DWKUL0188_N3_0330&cells[]=DWKUL0135_N3_0310
X-Requested-With: XMLHttpRequest
API: {{apiKey}}
Accept: application/text


###
#'DWKUL0739_L7_0030',
#                                               'DWKUL0314_L7_0010',
#                                               'DWKUL0405_L7_0030'
GET http://localhost:3001/node/dnb/v3/statsForCustomCellsListLTE?cells[]=DWKUL0739_L7_0010&cells[]=DWKUL0314_L7_0020
X-Requested-With: XMLHttpRequest
API: {{apiKey}}
Accept: application/text

###
# ?rand=52984.43&format=csv
GET http://localhost:3001/node/dnb/v3/networkDailyNR
X-Requested-With: XMLHttpRequest
API: {{apiKey}}
Accept: application/text

###
GET http://localhost:3001/node/dnb/v3/networkDailyPlmnNR
X-Requested-With: XMLHttpRequest
API: {{apiKey}}
Accept: application/text

###
GET http://localhost:3001/node/dnb/networkDailyNR
X-Requested-With: XMLHttpRequest
API: {{apiKey}}
Accept: application/text


###
GET https://api.eprojecttrackers.com/node/dnb/networkDailyNR
X-Requested-With: XMLHttpRequest
API: {{apiKey}}
Accept: application/text

###
GET http://localhost:3001/node/dnb/v3/networkDailyPlmnLTE
X-Requested-With: XMLHttpRequest
API: {{apiKey}}
Accept: application/json


###
GET http://localhost:3001/node/dnb/v3/networkDailyNR
X-Requested-With: XMLHttpRequest
API: {{apiKey}}
Accept: application/json


###
GET https://cmeportal.eprojecttrackers.com/ASPTracker.php?process=FRR&page=40&API={{apiKey}}
X-Requested-With: XMLHttpRequest
Accept: application/json



###
GET http://localhost:3001/node/dnb/v3/cellDailyPlmnLTE?cellId=DWKUL0489_L7_0030
X-Requested-With: XMLHttpRequest
API: {{apiKey}}
Accept: application/json



###
GET http://localhost:3001/node/dnb/v3/plmnDailyCellLTE?object=DBGBK0002_L7_0020
X-Requested-With: XMLHttpRequest
API: {{apiKey}}
Accept: application/json


###
GET http://localhost:3001/node/dnb/v3/plmnDailyNR
X-Requested-With: XMLHttpRequest
API: {{apiKey}}
Accept: application/json


###
GET http://localhost:3001/node/dnb/v3/plmnDailyCellNR?object=DBGBK1875_N3_0320
X-Requested-With: XMLHttpRequest
API: {{apiKey}}
Accept: application/json


###
GET http://localhost:3001/node/dnb/v3/networkDailyLTE?version=1.3
X-Requested-With: XMLHttpRequest
API: {{apiKey}}

Accept: application/json



###
GET http://localhost:3001/node/dnb/v3/networkDailyNRCell?object=DBGBK1875_N3_0330&version=1.2
X-Requested-With: XMLHttpRequest
API: {{apiKey}}
Accept: application/json


