const networkKpiList = {
    "NR": [
        "Cell Availability",
        "ENDC SR",
        "E-RAB Block Rate",
        "Erab Drop Call rate (sgNB)",
        "Intra-SgNB Pscell Change Success Rate",
        "Inter-SgNB PSCell Change Success Rate",
        "Resource Block Utilizing Rate (DL)",
        "Resource Block Utilizing Rate (UL)",
        "Average CQI",
        "UL BLER",
        "Avg PUSCH UL RSSI",
        "DL User Throughput",
        "UL User Throughput",
        "DL Cell Throughput",
        "UL Cell Throughput",
        "DL Data Volume",
        "UL Data Volume",
        "Max of RRC Connected User (ENDC)",
        "Max of Active User",
        "DL QPSK %",
        "DL 16QAM%",
        "DL 64QAM%",
        "DL 256QAM%",
        "UL QPSK %",
        "UL 16QAM%",
        "UL 64QAM%",
        "UL 256QAM%",
        "RRC Setup Success Rate (Signaling) (%)",
        "gNobeB CPU Load",
        "Packet Loss (DL)",
        "Packet Loss (UL)",
        "Latency (only Radio interface)",
        "NR_Avg_TA_Meters"
    ],
    "LTE": [
        "Cell Availability",
        "Call Setup Success Rate",
        "RRC Setup Success Rate (Service) (%)",
        "RRC Setup Success Rate (Signaling) (%)",
        "E-RAB Setup Success Rate_non-GBR (%)",
        "E-RAB Setup Success Rate (%)",
        "Erab Drop Call rate",
        "Handover In Success Rate",
        "UL BLER",
        "DL User Throughput",
        "UL User Throughput",
        "DL Cell Throughput",
        "UL Cell Throughput",
        "DL Data Volume",
        "UL Data Volume",
        "Max of RRC Connected User",
        "Max of Active User",
        "Packet Loss (DL)",
        "Packet Loss UL",
        "Latency (only Radio interface)",
        "DL QPSK %",
        "DL 16QAM%",
        "DL 64QAM%",
        "DL 256QAM%",
        "UL QPSK %",
        "UL 16QAM%",
        "UL 64QAM%",
        "UL 256QAM%",
        "Resource Block Utilizing Rate (DL)",
        "Resource Block Utilizing Rate (UL)",
        "Average CQI",
        "Avg PUSCH UL RSSI",
        "Intrafreq HOSR",
        "VoLTE Redirection Success Rate",
        "Interfreq HOSR",
        "LTE_Avg_TA_Meters",

    ]
};
const plmnKpiList = {
    'NR': [
        'ENDC SR',
        'Erab Drop Call rate (sgNB)',
        'Intra-SgNB Pscell Change Success Rate',
        'Inter-SgNB PSCell Change Success Rate',
        'Max of RRC Connected User (ENDC)',
        'DL User Throughput',
        'UL User Throughput',
        'DL Data Volume',
        'UL Data Volume',
        'DL QPSK %',
        'DL 16QAM%',
        'DL 64QAM%',
        'DL 256QAM%',
        'UL QPSK %',
        'UL 16QAM%',
        'UL 64QAM%'
    ],
    'LTE': [
        'E-RAB Setup Success Rate (%)',
        'Erab Drop Call rate',
        'Intrafreq HOSR',
        'UL BLER',
        'DL User Throughput',
        'UL User Throughput',
        'DL Cell Throughput',
        'UL Cell Throughput',
        'DL Data Volume',
        'UL Data Volume',
        'Packet Loss (DL)',
        'Packet Loss UL',
        'Latency (only Radio interface)',
        'DL QPSK %',
        'DL 16QAM%',
        'DL 64QAM%',
        'DL 256QAM%',
        'UL QPSK %',
        'UL 16QAM%',
        'UL 64QAM%',
        'UL 256QAM%',
        'E-RAB Setup Success Rate_non-GBR (%)',
        'Max of RRC Connected User'
    ],
}


module.exports = {
    networkKpiList,
    plmnKpiList,
}